# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Project
        uses: actions/checkout@v5
        with:
          path: himenosena

      - name: Checkout kurobidder Dependency
        uses: actions/checkout@v5
        with:
          repository: peter910820/seaotterms-db
          path: seaotterms-db

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24.0"

      - name: Build
        run: |
          cd himenosena
          go mod edit -replace seaotterms-db=../seaotterms-db
          
          export GOPROXY=direct
          
          go mod tidy
          
          go build -v ./...
